sudo: required
services:
    - docker
env:
    global: 
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
    #google cloud specifics
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in multi-k8s-269100-dfdb58b4df9b.json.enc -out multi-k8s-269100-dfdb58b4df9b.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc    
    #gcloud get kubectl
    - gcloud components update kubectl
    #authenticate
    - gcloud auth activate-service-account --key-file multi-k8s-269100-dfdb58b4df9b.json
    #- gcloud config set account travis-deployer@multi-k8s-269100.iam.gserviceaccount.com
    #self descriptive
    - gcloud config set project multi-k8s-269100    
    - gcloud config set compute/zone us-central1-c
    - gcloud container clusters get-credentials multi-cluster
    #login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #build tests container
    - docker build -t dannx/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dannx/react-test npm run test

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master
